package tui

const Currency = "Currency"
const DefaultCurrency = "Default currency"
const Name = "Name"
const InitialAmount = "Initial amount"
const UseInBudget = "Use in budget"
const FirstDayOfMonth = "First day of month"
const Account = "Account"
const Amount = "Amount"
const Description = "Description"
const Category = "Category"

const App = "app"
const Pages = "pages"
const Menu = "menu"
const BudegtInfo = "budgetInfo"
const DetailsFrame = "detalisFrame"
const MainGrid = "mainGrid"
const HelpInfo = "helpInfo"
const HelpFrame = "helpFrame"
const NewBudgetForm = "newBudgetForm"
const NewAccountForm = "newAccountForm"
const TransferForm = "transferForm"
const QuickIncomeForm = "quickIncomeForm"
const QuickOutcomeForm = "quickOutComeForm"
